apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  app.kubernetes.io/component: cert-manager
  app.kubernetes.io/name: cert-manager
  kustomize.component: cert-manager
kind: Kustomization
#namespace: cert-manager
resources:
#This is downloaded from https://github.com/jetstack/cert-manager/releases/download/v1.5.0/cert-manager.yaml
- cert-manager-1.5.yaml
- cert-manager/cert-manager/overlays/self-signed
